apiVersion: v1
kind: Service
metadata:
  name: hello-world-webserver-service
spec:
  selector:
    app: hello-world-webserver-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
